### ISSUE TITLE
SÍNTESIS DE GESTIÓN DE LA CALIDAD DE PROYECTOS DE SOFTWARE  

### ISSUE THREAD

**Issue by uzias10** [SistemasTecTlaxiaco/actividad-4-tarea-de-sintesis-de-calidad-uzias10#1]
[SINTESIS GESTIÓN DE LA CALIDAD DE PROYECTOS DE SOFTWARE.pdf](https://github.com/SistemasTecTlaxiaco/actividad-4-tarea-de-sintesis-de-calidad-uzias10/files/9569401/SINTESIS.GESTION.DE.LA.CALIDAD.DE.PROYECTOS.DE.SOFTWARE.pdf)

**Comment by carlos-chrs** [comment]
Revisado 20/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
